const APP='TorqueForge Field Command';
const modules=[['home','🏠','HOME'],['ai','🤖','AI'],['parts','⚙️','PARTS'],['jobs','📋','JOBS'],['more','•••','MORE']];
const drawerItems=[['home','Dashboard'],['ai','Ask Field AI'],['parts','Parts / Cross Ref'],['vin','VIN / Equipment'],['doctor','Fault Doctor'],['repair','Repair HUD'],['customers','Customers'],['jobs','Jobs / Work Orders'],['quotes','Quotes / Invoices'],['clock','Time Clock'],['photos','Photos / OCR'],['schedule','Schedule'],['reports','Reports'],['settings','Settings']];
const $=id=>document.getElementById(id), store={get(k,d){try{return JSON.parse(localStorage.getItem(k))??d}catch(e){return d}},set(k,v){localStorage.setItem(k,JSON.stringify(v))}};
let state=store.get('state',{settings:{shop:'Rolling Wrench Diesel',phone:'260-502-6222',rate:135,service:250,tax:7,markup:15,theme:'orange'},truck:{},customer:{},clock:{running:false,start:0,elapsed:0},jobs:[],photos:[],chat:[]});
function money(n){return '$'+Number(n||0).toFixed(2)} function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function save(){store.set('state',state); toast('Saved on this device')} function toast(t){let d=document.createElement('div');d.textContent=t;d.style.cssText='position:fixed;left:14px;right:14px;bottom:78px;background:#111;border:1px solid #444;padding:12px;border-radius:14px;z-index:20';document.body.appendChild(d);setTimeout(()=>d.remove(),1800)}
function nav(){drawer.innerHTML='<h2>TorqueForge</h2><p class="muted">New public-ready shell built from the best old modules.</p>'+drawerItems.map(x=>`<button class="icon" onclick="show('${x[0]}');drawer.classList.remove('open')">${x[1]}</button>`).join('');tabs.innerHTML=modules.map(x=>`<button data-tab="${x[0]}" onclick="show('${x[0]}')">${x[1]}<b>${x[2]}</b></button>`).join('')}
function show(id){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));let el=$(id); if(!el){id='home';el=$(id)} el.classList.add('active');document.querySelectorAll('#tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===id)); window.scrollTo(0,0); renderDynamic()}
function screens(){screens.innerHTML=`
<section id="home" class="screen active"><h1>Field Command</h1><div class="grid"><div class="card"><h3>Active Job</h3><b>${esc(activeJob()?.title||'No job selected')}</b><p class="muted">Clock: <span id="miniClock">00:00:00</span></p><button class="btn" onclick="show('jobs')">Open Jobs</button></div><div class="card"><h3>Active Truck / Equipment</h3><b>${esc(truckTitle())}</b><p class="muted">VIN/Serial: ${esc(state.truck.vin||'optional')}</p><button class="btn" onclick="show('vin')">Truck Profile</button></div><div class="card"><h3>Weekly Money</h3><b class="good" id="weekMoney">$0.00</b><p class="muted">Labor tracked from clock/job hours.</p><button class="btn" onclick="show('reports')">Reports</button></div></div><h3 style="margin-top:16px">Tools</h3><div class="grid">${drawerItems.slice(1).map(x=>`<button class="card tile" onclick="show('${x[0]}')"><span>${x[1].split(' ')[0]}</span><b>${x[1]}</b><small>Open module</small></button>`).join('')}</div></section>
<section id="ai" class="screen"><h2>Ask Field AI</h2><div class="card chat"><div id="chatLog"></div><textarea id="aiInput" placeholder="Ask repair, parts, quote, fault code, customer message..."></textarea><div class="row"><button class="btn" onclick="askAI()">Ask</button><button class="btn ghost" onclick="voice('aiInput')">🎙 Voice</button></div><button class="btn ghost" onclick="state.chat=[];save();renderDynamic()">Clear Chat</button></div></section>
<section id="parts" class="screen"><h2>Parts / Cross Reference</h2><div class="card"><input id="partQ" placeholder="Part number, VIN, engine, symptom"><textarea id="partNote" placeholder="Extra notes, old part number, supplier, measurements"></textarea><button class="btn" onclick="partsSearch()">Build Parts Search</button><div id="partsOut" class="out"></div></div></section>
<section id="vin" class="screen"><h2>VIN / Equipment</h2><div class="card row"><input id="tname" placeholder="Truck/equipment name" value="${esc(state.truck.name||'')}"><input id="tvin" placeholder="VIN / serial optional" value="${esc(state.truck.vin||'')}"><input id="tengine" placeholder="Engine" value="${esc(state.truck.engine||'')}"><input id="tmiles" placeholder="Miles / hours" value="${esc(state.truck.miles||'')}"><button class="btn" onclick="saveTruck()">Save Active Unit</button></div></section>
<section id="doctor" class="screen"><h2>Fault Doctor</h2><div class="card"><textarea id="fault" placeholder="SPN/FMI, code, complaint, readings..."></textarea><button class="btn" onclick="faultDoctor()">Build Diagnostic Plan</button><div id="faultOut" class="out"></div></div></section>
<section id="repair" class="screen"><h2>Repair HUD</h2><div class="card"><textarea id="repairInput" placeholder="Repair task"></textarea><button class="btn" onclick="repairPlan()">Build Repair Checklist</button><div id="repairOut" class="out"></div></div></section>
<section id="customers" class="screen"><h2>Customers</h2><div class="card row"><input id="cname" placeholder="Customer name" value="${esc(state.customer.name||'')}"><input id="cphone" placeholder="Phone" value="${esc(state.customer.phone||'')}"><input id="cemail" placeholder="Email" value="${esc(state.customer.email||'')}"><button class="btn" onclick="saveCustomer()">Save Active Customer</button></div></section>
<section id="jobs" class="screen"><h2>Jobs / Work Orders</h2><div class="card"><input id="jobTitle" placeholder="Job title"><textarea id="jobNotes" placeholder="Complaint / work performed / parts needed"></textarea><button class="btn" onclick="addJob()">Add Job</button><div id="jobList"></div></div></section>
<section id="quotes" class="screen"><h2>Quotes / Invoices</h2><div class="card row3"><input id="qdesc" placeholder="Work description"><input id="qhours" type="number" step=".1" placeholder="Hours"><input id="qparts" type="number" step=".01" placeholder="Parts cost"><button class="btn" onclick="buildInvoice('quote')">Build Quote</button><button class="btn" onclick="buildInvoice('invoice')">Build Invoice</button><button class="btn ghost" onclick="window.print()">Print / Save PDF</button></div><div id="invoiceOut" class="paper"></div><canvas id="sig" class="sig noPrint"></canvas><button class="btn ghost noPrint" onclick="clearSig()">Clear Signature</button></section>
<section id="clock" class="screen"><h2>Time Clock</h2><div class="card"><h1 id="clockBig">00:00:00</h1><div class="row3"><button class="btn" onclick="clockStart()">Start</button><button class="btn ghost" onclick="clockPause()">Pause</button><button class="btn danger" onclick="clockStop()">Stop</button></div><p class="muted">Tracks labor for the active job. No auto-start.</p></div></section>
<section id="photos" class="screen"><h2>Photos / OCR</h2><div class="card"><input id="photoIn" type="file" accept="image/*" capture="environment"><textarea id="photoNote" placeholder="What should this photo be used for? Part receipt, fault screen, work photo..."></textarea><button class="btn" onclick="savePhoto()">Save Photo Note</button><div id="photoList"></div></div></section>
<section id="schedule" class="screen"><h2>Schedule</h2><div class="card"><input id="appt" placeholder="Example: Friday 4 PM - DPF regen"><button class="btn" onclick="addSchedule()">Add</button><div id="schedList" class="out"></div></div></section>
<section id="reports" class="screen"><h2>Reports</h2><div class="card out" id="reportOut"></div></section>
<section id="settings" class="screen"><h2>Settings</h2><div class="card row"><input id="sShop" value="${esc(state.settings.shop)}"><input id="sPhone" value="${esc(state.settings.phone)}"><input id="sRate" type="number" value="${state.settings.rate}"><input id="sService" type="number" value="${state.settings.service}"><input id="sTax" type="number" value="${state.settings.tax}"><input id="sMarkup" type="number" value="${state.settings.markup}"><select id="sTheme"><option>orange</option><option>green</option><option>red</option><option>light</option></select><button class="btn" onclick="saveSettings()">Save Settings</button></div></section>`; sigSetup()}
function renderDynamic(){let log=$('chatLog'); if(log)log.innerHTML=state.chat.map(m=>`<div class="msg ${m.me?'me':''}">${esc(m.text)}</div>`).join(''); let jl=$('jobList'); if(jl)jl.innerHTML=state.jobs.map((j,i)=>`<div class="card"><b>${esc(j.title)}</b><p class="muted">${esc(j.notes)}</p><button class="btn ghost" onclick="setActiveJob(${i})">Make Active</button></div>`).join(''); let pl=$('photoList'); if(pl)pl.innerHTML=state.photos.map(p=>`<div class="card"><b>${esc(p.note)}</b><p class="muted">${esc(p.date)}</p></div>`).join(''); let sl=$('schedList'); if(sl)sl.textContent=(state.schedule||[]).join('\n'); let ro=$('reportOut'); if(ro)ro.textContent=`Shop: ${state.settings.shop}\nJobs: ${state.jobs.length}\nPhotos saved: ${state.photos.length}\nClock hours: ${(state.clock.elapsed/3600000).toFixed(2)}\nLabor value: ${money((state.clock.elapsed/3600000)*state.settings.rate)}`; updateClock()}
function truckTitle(){return state.truck.name||[state.truck.year,state.truck.make,state.truck.model,state.truck.engine].filter(Boolean).join(' ')||'No active unit'} function activeJob(){return state.jobs.find(j=>j.active)}
function askAI(){let q=$('aiInput').value.trim(); if(!q)return; state.chat.push({me:1,text:q}); state.chat.push({text:`Field answer draft:\n• Active unit: ${truckTitle()}\n• Customer: ${state.customer.name||'none'}\n• First verify complaint, power/ground, codes, and service info.\n• For public release this module should call your Render/OpenAI/Supabase backend.\n• Save confirmed fix to Repair Memory after testing.`}); $('aiInput').value=''; save(); renderDynamic()}
function partsSearch(){let q=$('partQ').value, n=$('partNote').value; $('partsOut').textContent=`Search package:\nPart/request: ${q}\nUnit: ${truckTitle()}\nVIN/Serial: ${state.truck.vin||'optional'}\nNotes: ${n}\nReturn fields needed: OEM number, supersessions, crosses, local suppliers, price, confidence, source link, and exact-fit warning.`}
function saveTruck(){state.truck={name:$('tname').value,vin:$('tvin').value,engine:$('tengine').value,miles:$('tmiles').value};save();screens();show('vin')} function saveCustomer(){state.customer={name:$('cname').value,phone:$('cphone').value,email:$('cemail').value};save();toast('Customer saved')}
function faultDoctor(){let f=$('fault').value; $('faultOut').textContent=`Diagnostic plan for: ${f}\n1. Confirm complaint and active/inactive faults.\n2. Record KOEO/idle/load readings.\n3. Check powers, grounds, 5V reference, sensor return, and data link.\n4. Inspect connectors, harness rubs, corrosion, and recent repairs.\n5. Run OEM test plan. Do not replace parts until failed test is proven.\n6. Save confirmed fix and parts used.`}
function repairPlan(){let r=$('repairInput').value; $('repairOut').textContent=`Repair checklist: ${r}\n• Safety/LOTO/chock wheels.\n• Confirm parts and fluids before teardown.\n• Take before photos.\n• Track time and parts.\n• Torque/adjust/relearn/calibrate as needed.\n• Test operation.\n• Add warranty/disclaimer notes to invoice.`}
function addJob(){state.jobs.forEach(j=>j.active=false); state.jobs.unshift({title:$('jobTitle').value||'Untitled Job',notes:$('jobNotes').value,active:true,date:new Date().toLocaleString()});save();renderDynamic()} function setActiveJob(i){state.jobs.forEach((j,n)=>j.active=n===i);save();renderDynamic()}
function buildInvoice(type){let s=state.settings,h=Number($('qhours').value||0),parts=Number($('qparts').value||0),labor=h*s.rate,svc=Number(s.service||0),marked=parts*(1+s.markup/100),tax=marked*(s.tax/100),total=labor+svc+marked+tax; $('invoiceOut').innerHTML=`<h2>${esc(s.shop)} ${type.toUpperCase()}</h2><p>Phone: ${esc(s.phone)}<br>Customer: ${esc(state.customer.name||'')}<br>Unit: ${esc(truckTitle())}<br>VIN/Serial: ${esc(state.truck.vin||'')}</p><table><tr><th>Description</th><th>Amount</th></tr><tr><td>${esc($('qdesc').value||'Labor / repair service')}</td><td>${money(labor)}</td></tr><tr><td>Service call</td><td>${money(svc)}</td></tr><tr><td>Parts with ${s.markup}% markup</td><td>${money(marked)}</td></tr><tr><td>Estimated IN sales tax on parts</td><td>${money(tax)}</td></tr><tr><th>Total</th><th>${money(total)}</th></tr></table><p><b>Signature required:</b> ____________________________</p><small>Prices may change if hidden damage, wrong parts, supplier price change, extra labor, or additional diagnostics are required.</small>`}
function clockStart(){if(!state.clock.running){state.clock.running=true;state.clock.start=Date.now();save()}} function clockPause(){if(state.clock.running){state.clock.elapsed+=Date.now()-state.clock.start;state.clock.running=false;save();updateClock()}} function clockStop(){clockPause();toast('Clock stopped')} function updateClock(){let e=state.clock.elapsed+(state.clock.running?Date.now()-state.clock.start:0), h=Math.floor(e/3600000),m=Math.floor(e/60000)%60,s=Math.floor(e/1000)%60,t=[h,m,s].map(x=>String(x).padStart(2,'0')).join(':'); ['clockBig','miniClock'].forEach(id=>{if($(id))$(id).textContent=t}); if($('weekMoney'))$('weekMoney').textContent=money((e/3600000)*state.settings.rate)} setInterval(updateClock,1000)
function savePhoto(){state.photos.unshift({note:$('photoNote').value||'Photo saved',date:new Date().toLocaleString()});save();renderDynamic()} function addSchedule(){state.schedule=state.schedule||[];state.schedule.unshift($('appt').value);save();renderDynamic()} function saveSettings(){state.settings={shop:$('sShop').value,phone:$('sPhone').value,rate:Number($('sRate').value),service:Number($('sService').value),tax:Number($('sTax').value),markup:Number($('sMarkup').value),theme:$('sTheme').value};save();screens();show('settings')}
function voice(id){let SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR)return toast('Voice not supported on this browser');let r=new SR();r.onresult=e=>{$(id).value+=(e.results[0][0].transcript)};r.start()} let sigCtx,drawing=false; function sigSetup(){let c=$('sig'); if(!c)return; sigCtx=c.getContext('2d'); c.width=c.clientWidth; c.height=160; c.onpointerdown=e=>{drawing=true;sigCtx.moveTo(e.offsetX,e.offsetY)}; c.onpointermove=e=>{if(drawing){sigCtx.lineTo(e.offsetX,e.offsetY);sigCtx.stroke()}}; c.onpointerup=()=>drawing=false} function clearSig(){let c=$('sig');sigCtx.clearRect(0,0,c.width,c.height)}
menuBtn.onclick=()=>drawer.classList.toggle('open'); saveBtn.onclick=save; nav(); screens(); show('home'); if('serviceWorker' in navigator)navigator.serviceWorker.register('service-worker.js').catch(()=>{});